const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://i.pinimg.com/564x/a4/f5/63/a4f56379768c2f9eccd33c3e23f0055e.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://i.pinimg.com/474x/46/9c/fc/469cfc4bb5ff1c832fc9e06976bfa14f.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://i.pinimg.com/564x/af/b0/20/afb0200661e7ff3301025f312a45377e.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'Waffles',
      category: 'breakfast',
      price: 20.99,
      img: 'https://i.pinimg.com/564x/eb/01/47/eb01472cc23f4445b2825041c817be53.jpg',
      desc: `Enjoy delicious, light and fluffy waffles any day of the week! Made with our Baking & Pancake Mix.`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://i.pinimg.com/564x/0a/6c/61/0a6c616be17114ed1873273c9f6002d9.jpg',
      desc: `Lamb Tagine is my pick of all tagines! The ras el hanout spice mix is sheer perfection with lamb, and slow cooking works wonders to develop rich flavours in the sauce. Serve over couscous for a stunning Moroccan meal. `,
    },
    {
      id: 6,
      title: '',
      category: 'shakes',
      price: 18.99,
      img: 'https://i.pinimg.com/474x/a5/32/36/a53236f20d1c82fc16f0c153473ec837.jpg',
      desc: `This vegan protein shake doesn't require any protein powder. It's creamy, chocolatey and delicious with 20 grams of protein per serve! `,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://i.pinimg.com/564x/55/8f/71/558f71ee98cbc4a5d2faa66055024920.jpg',
      desc: `This bacon puff pastry twist homemade style is a great picnic food idea or brunch idea. `,
    },
    {
      id: 8,
      title: 'One pot creamy tomato beef pasta',
      category: 'lunch',
      price: 12.99,
      img: 'https://i.pinimg.com/474x/8e/95/e2/8e95e2353e5442ca636d2d0a4b81eb19.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Chocolate Cherry Smoothie',
      category: 'shakes',
      price: 16.99,
      img: 'https://i.pinimg.com/564x/a0/13/e4/a013e4a73e2dff95b4c96f289c962720.jpg',
      desc: `Sweet and juicy cherries blended with your favourite milk, cocoa powder and bananas to thicken make a rich and delicious Chocolate Cherry Smoothie that the whole family will love`,
    },
  ];
  export default menu;